# CAPI Automatic Evaluation — BERTScore and ROUGE-L

This notebook computes the automatic evaluation metrics for the five response-generation configurations (**LLM-only, LLM+RAG, and LLM+RAG+PA at Top-1, Top-3, and Top-5**).

* **BERTScore (F1)** — measures the semantic similarity between each generated response and its corresponding ground-truth answer using contextual embeddings.
* **ROUGE-L (F1)** — measures lexical similarity based on the longest common subsequence (LCS) between the generated response and the reference answer.

**Measurement decisions**:

* The **F1 score** is reported for both BERTScore and ROUGE-L to provide a balanced measure of precision and recall.
* Each chatbot response is compared against a single ground-truth answer.
* Scores are computed independently for every response and then aggregated for each configuration.

Requires: `transformers`, `evaluate`, `rouge-score` (`pip install evaluate rouge-score`).

In [1]:
from transformers.utils import logging
logging.set_verbosity_error()

In [2]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (3.32.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.24.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 940.1 kB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [3]:
pip install rouge-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rouge-score) (2.1.3)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->rouge-score) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk->rouge-score) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk->rouge-score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk->rouge-score) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk->rouge-score) (3.1.2)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24986 sha256=b2fcff8a55fecfeacf3855fec3777316ff6e279c9d84fe42af103c812fb2bdbd
  Stored in directory: /root/.cache/pip/wheels/44/af/da/5ffc433e2786f0b1a9c6f458d5fb8f611d8eb332387f18698f
Successfully built rouge-score
Installing collected packages: rouge-score
Successfully installed rouge-score-0.1.2

In [4]:
pip install bert_score

Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from bert_score) (2.11.0+cpu)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from bert_score) (2.2.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from bert_score) (5.16.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from bert_score) (2.1.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from bert_score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.13/dist-packages (from bert_score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from bert_score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from bert_score) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.1->bert_score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.1->bert_score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.1->bert_score) (2026.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.0.0->bert_score) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=3.0.0->bert_score) (1.29.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers>=3.0.0->bert_score) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers>=3.0.0->bert_score) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers>=3.0.0->bert_score) (0.23.1)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers>=3.0.0->bert_score) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=3.0.0->bert_score) (0.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->bert_score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->bert_score) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->bert_score) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->bert_score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->bert_score) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->bert_score) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->bert_score) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->bert_score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->bert_score) (2026.7.22)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert_score) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert_score) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert_score) (0.28.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.0.0->bert_score) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=3.0.0->bert_score) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=3.0.0->bert_score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=3.0.0->bert_score) (0.0.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert_score) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert_score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert_score) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers>=3.0.0->bert_score) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers>=3.0.0->bert_score) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=3.0.0->bert_score) (0.1.2)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 713.5 kB/s eta 0:00:00
Installing collected packages: bert_score
Successfully installed bert_score-0.3.13

In [5]:
from google.colab import drive
import os
drive.mount('/content/drive')
dataset_dir = "drive/MyDrive/CAPI---Chatbot-Informatics-main"
os.chdir(dataset_dir)

Mounted at /content/drive

In [6]:
import pandas as pd
import csv

df = pd.read_csv("./03_Data/Groundtruth.csv")
# Display the first few rows of the DataFrame to verify
display(df.head())

,Query,question,Ground truth,Kategori,Top 3,Top1,Top5,LLMOnly,RAG
0,1,Informatika itu apa?,Informatika di UHN Sugriwa adalah program stud...,Profil,Halo! Senang bertemu di UHN Sugriwa! Informati...,Halo! Informatika itu ilmu yang asyik banget n...,Hai! Senang bisa bantu ya. Informatika itu kay...,**Informatika adalah ilmu dan seni yang mempel...,**Jawaban:**\n\nInformatika adalah ilmu yang m...
1,2,Nanti anak saya kalau mau kuliah informatika b...,Berkuliah di Informatika akan belajar mengenai...,Belajar apa?,Halo! Senang sekali mendengar minat Bapak/Ibu ...,Halo! Senang sekali mendengar kamu tertarik de...,Halo! Senang sekali mendengar kamu tertarik sa...,Untuk mempersiapkan anak Anda menghadapi studi...,Untuk menanggapi pertanyaan Anda mengenai mata...
2,3,Peluang kerja ketika lulusan informatika,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Halo! Senang sekali kamu tertarik dengan jurus...,"Halo! Wah, senang sekali kamu tertarik dengan ...",Halo! Senang sekali kamu tertarik sama jurusan...,"Halo! Sebagai lulusan Informatika, peluang kar...",Halo! Terima kasih atas pertanyaannya. Berdasa...
3,4,Apa saja peluang pekerjaannya?,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Hai! Senang sekali kamu tertarik sama jurusan ...,"Hai! Wah, senang sekali kamu tertarik sama jur...",Halo! Senang sekali kamu tertarik dengan jurus...,"Halo! Pertanyaan yang bagus. ""Peluang kerja"" b...",Selamat! Sebagai lulusan Prodi Informatika Uni...
4,5,Skil apa yang harus dimiliki jika mau jadi fro...,"Untuk menjadi Front-End Developer, perlu mengu...",Umum,Hai! Senang banget kamu tertarik jadi *front-e...,Hai! Senang banget kamu tertarik jadi *front-e...,Hai! Senang banget kamu tertarik jadi *front-e...,Untuk menjadi *front-end developer* (pengemban...,Untuk menjadi *front-end developer* yang kompe...

In [7]:
# select non na data
total_data = df[(df['Query'].notna())]

In [8]:
# filter data is not na
ground_nan = total_data[(total_data['Ground truth'].isna())]

In [9]:
# select data is not na
filtered_ground_truth = df[(df['Ground truth'].notna())]

In [10]:
# check total data
len(total_data)

265

In [11]:
# select data based on the category
top_1 = filtered_ground_truth["Top1"].to_list()
top_3 = filtered_ground_truth["Top 3"].to_list()
top_5 = filtered_ground_truth["Top5"].to_list()
llm_only = filtered_ground_truth["LLMOnly"].to_list()
llm_rag_only = filtered_ground_truth["RAG"].to_list()
ground_truth = filtered_ground_truth["Ground truth"].to_list()

In [12]:
top_1[0]

'Halo! Informatika itu ilmu yang asyik banget nih, soal cara ngolah data pakai komputer. Di UHN Sugriwa, kita belajar bikin aplikasi, sistem pintar kayak AI, dan juga cari solusi teknologi yang sesuai sama budaya kita. Jadi gampangnya, informatika itu kayak bumbu rahasia buat bikin dunia digital makin canggih! Semoga kamu suka ya di sini!'

In [13]:
ground_truth[0]

'Informatika di UHN Sugriwa adalah program studi yang menghasilkan lulusan yang mampu menciptakan perangkat lunak, aplikasi bidang AI, atau teknologi lainnya, atau disebut juga Lulusan bisa bekerja sebagai AI Engineer, Software Engineer, Asisten Peneliti. Sehingga bisa membantu mempermudah kehidupan atau pekerjaan masyarakat. '

In [14]:
import re
import string
# menormalisasikan data biar sama formatnya, lowercase, tanpa punctuation dan dibersihkan empty string
# text normalization to  the same format, lowercase, remove punctuation and clear empty string
def normalize_text(s):
    s = s.lower()

    # replace punctuation with space, not empty string
    s = "".join(" " if ch in string.punctuation else ch for ch in s)

    # fix whitespace
    s = re.sub(r"\s+", " ", s).strip()

    return s

In [15]:
import evaluate

rouge_metric = evaluate.load("rouge")

def calculate_rouge_l(predictions, ground_truths):
    predictions = [normalize_text(x) for x in predictions]
    ground_truths = [normalize_text(x) for x in ground_truths]

    result = rouge_metric.compute(
        predictions=predictions,
        references=ground_truths
    )

    return result["rougeL"] * 100

Downloading builder script: 0.00B [00:00, ?B/s]

In [16]:
# clean empty string
def normalize_for_bertscore(s):
    return re.sub(r"\s+", " ", s).strip()

In [17]:
import evaluate

bertscore = evaluate.load("bertscore")

def calculate_bertscore(predictions, ground_truths):
    predictions = [normalize_for_bertscore(x) for x in predictions]
    ground_truths = [normalize_for_bertscore(x) for x in ground_truths]

    if len(predictions) == 0:
        return 0.0

    '''result = bertscore.compute(
        predictions=predictions,
        references=ground_truths,
        lang="id"
    )'''

    result = bertscore.compute(
        predictions=predictions,
        references=ground_truths,
        lang="id",
    )

    return sum(result["f1"]) / len(result["f1"]) * 100

Downloading builder script: 0.00B [00:00, ?B/s]

In [18]:
import pandas as pd
import evaluate
import re

# Helper function for normalizing text (moved from xAgXPZuAXGIg)
def normalize_for_bertscore(s):
    if s is None: # Handle None values which might result from pd.isna check
        return ""
    return re.sub(r"\s+", " ", str(s)).strip()

bertscore_metric = evaluate.load("bertscore")

def calculate_single_bertscore_f1(prediction, reference):
    # Ensure prediction and reference are strings and not NaN
    if pd.isna(prediction) or pd.isna(reference):
        return None # Or 0.0, depending on how you want to handle missing values

    prediction = normalize_for_bertscore(prediction)
    reference = normalize_for_bertscore(reference)

    # If either is empty after normalization, BERTScore might fail or not be meaningful
    if not prediction or not reference:
        return None

    # bertscore.compute expects lists of predictions and references
    result = bertscore_metric.compute(
        predictions=[prediction],
        references=[reference],
        lang="id"
    )
    return result["f1"][0] * 100 # Return the single F1 score

calculate the BERTScore for each prediction type against the ground truth and add these as new columns to the `filtered_ground_truth` DataFrame.

In [19]:
# Calculate BERTScore for each prediction type per row
filtered_ground_truth['Top1_BERTScore'] = filtered_ground_truth.apply(lambda row: calculate_single_bertscore_f1(row['Top1'], row['Ground truth']), axis=1)
filtered_ground_truth['Top3_BERTScore'] = filtered_ground_truth.apply(lambda row: calculate_single_bertscore_f1(row['Top 3'], row['Ground truth']), axis=1)
filtered_ground_truth['Top5_BERTScore'] = filtered_ground_truth.apply(lambda row: calculate_single_bertscore_f1(row['Top5'], row['Ground truth']), axis=1)
filtered_ground_truth['LLMOnly_BERTScore'] = filtered_ground_truth.apply(lambda row: calculate_single_bertscore_f1(row['LLMOnly'], row['Ground truth']), axis=1)
filtered_ground_truth['RAG_BERTScore'] = filtered_ground_truth.apply(lambda row: calculate_single_bertscore_f1(row['RAG'], row['Ground truth']), axis=1)

# Display the DataFrame with new BERTScore columns
display(filtered_ground_truth.head())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  714MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

,Query,question,Ground truth,Kategori,Top 3,Top1,Top5,LLMOnly,RAG,Top1_BERTScore,Top3_BERTScore,Top5_BERTScore,LLMOnly_BERTScore,RAG_BERTScore
0,1,Informatika itu apa?,Informatika di UHN Sugriwa adalah program stud...,Profil,Halo! Senang bertemu di UHN Sugriwa! Informati...,Halo! Informatika itu ilmu yang asyik banget n...,Hai! Senang bisa bantu ya. Informatika itu kay...,**Informatika adalah ilmu dan seni yang mempel...,**Jawaban:**\n\nInformatika adalah ilmu yang m...,68.463814,70.124251,68.724281,63.069034,69.222838
1,2,Nanti anak saya kalau mau kuliah informatika b...,Berkuliah di Informatika akan belajar mengenai...,Belajar apa?,Halo! Senang sekali mendengar minat Bapak/Ibu ...,Halo! Senang sekali mendengar kamu tertarik de...,Halo! Senang sekali mendengar kamu tertarik sa...,Untuk mempersiapkan anak Anda menghadapi studi...,Untuk menanggapi pertanyaan Anda mengenai mata...,71.410537,73.420596,68.329823,67.942017,67.797756
2,3,Peluang kerja ketika lulusan informatika,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Halo! Senang sekali kamu tertarik dengan jurus...,"Halo! Wah, senang sekali kamu tertarik dengan ...",Halo! Senang sekali kamu tertarik sama jurusan...,"Halo! Sebagai lulusan Informatika, peluang kar...",Halo! Terima kasih atas pertanyaannya. Berdasa...,69.110465,70.974064,71.381390,60.728037,62.316221
3,4,Apa saja peluang pekerjaannya?,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Hai! Senang sekali kamu tertarik sama jurusan ...,"Hai! Wah, senang sekali kamu tertarik sama jur...",Halo! Senang sekali kamu tertarik dengan jurus...,"Halo! Pertanyaan yang bagus. ""Peluang kerja"" b...",Selamat! Sebagai lulusan Prodi Informatika Uni...,70.654625,71.020824,71.377748,61.869234,64.038795
4,5,Skil apa yang harus dimiliki jika mau jadi fro...,"Untuk menjadi Front-End Developer, perlu mengu...",Umum,Hai! Senang banget kamu tertarik jadi *front-e...,Hai! Senang banget kamu tertarik jadi *front-e...,Hai! Senang banget kamu tertarik jadi *front-e...,Untuk menjadi *front-end developer* (pengemban...,Untuk menjadi *front-end developer* yang kompe...,70.632434,71.192479,65.895331,65.287858,63.480312

save the DataFrame with the new BERTScore columns to a CSV file.

In [20]:
# Save the updated DataFrame to a new CSV file
save_dir = "response_uhn_chatbot"
os.makedirs(save_dir, exist_ok=True)
output_csv_path = save_dir + "/Groundtruth_BERTScore_per_query.csv"
filtered_ground_truth.to_csv(output_csv_path, index=False)
print(f"DataFrame with per-query BERTScore saved to: {output_csv_path}")

DataFrame with per-query BERTScore saved to: response_uhn_chatbot/Groundtruth_BERTScore_per_query.csv

In [21]:
top_1_rouge = calculate_rouge_l(top_1, ground_truth)
top_3_rouge = calculate_rouge_l(top_3, ground_truth)
top_5_rouge = calculate_rouge_l(top_5, ground_truth)
llm_only_rouge = calculate_rouge_l(llm_only, ground_truth)
llm_rag_only_rouge = calculate_rouge_l(llm_rag_only, ground_truth)

In [22]:
print(f"top 1 rougeL: {top_1_rouge}")
print(f"top 3 rougeL: {top_3_rouge}")
print(f"top 5 rougeL: {top_5_rouge}")
print(f"llm only rougeL: {llm_only_rouge}")
print(f"llm rag only rougeL: {llm_rag_only_rouge}")

top 1 rougeL: 14.419672533708422
top 3 rougeL: 15.308334305546174
top 5 rougeL: 14.417062217098325
llm only rougeL: 10.613711268999717
llm rag only rougeL: 12.538060400071855

In [23]:
top_1_bertscore = calculate_bertscore(top_1, ground_truth)
top_3_bertscore = calculate_bertscore(top_3, ground_truth)
top_5_bertscore = calculate_bertscore(top_5, ground_truth)
llm_only_bertscore = calculate_bertscore(llm_only, ground_truth)
llm_rag_only_bertscore = calculate_bertscore(llm_rag_only, ground_truth)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [24]:
print(f"top 1 bertscore: {top_1_bertscore}")
print(f"top 3 bertscore: {top_3_bertscore}")
print(f"top 5 bertscore: {top_5_bertscore}")
print(f"llm only bertscore: {llm_only_bertscore}")
print(f"llm rag only bertscore: {llm_rag_only_bertscore}")

top 1 bertscore: 68.14722056658763
top 3 bertscore: 68.26763339762417
top 5 bertscore: 67.92275446765828
llm only bertscore: 64.90587435803323
llm rag only bertscore: 66.33823527480072

In [25]:
import pandas as pd

results = {
    "Model": ["Top 1", "Top 3", "Top 5", "LLM Only", "LLM RAG Only"],
    "ROUGE_L": [top_1_rouge, top_3_rouge, top_5_rouge, llm_only_rouge, llm_rag_only_rouge],
    "BERTScore": [top_1_bertscore, top_3_bertscore, top_5_bertscore, llm_only_bertscore, llm_rag_only_bertscore]
}

df_results = pd.DataFrame(results)
print(df_results)

          Model    ROUGE_L  BERTScore
0         Top 1  14.419673  68.147221
1         Top 3  15.308334  68.267633
2         Top 5  14.417062  67.922754
3      LLM Only  10.613711  64.905874
4  LLM RAG Only  12.538060  66.338235

calculate the ROUGE-L for each prediction type against the ground truth and add these as new columns to the `filtered_ground_truth` DataFrame.

In [26]:
import pandas as pd
import evaluate
import re
import string

# Helper function for normalizing text (copied from sDORUpMDXA52)
def normalize_text_single(s):
    if pd.isna(s):
        return ""
    s = str(s).lower()
    # replace punctuation with space, not empty string
    s = "".join(" " if ch in string.punctuation else ch for ch in s)
    # fix whitespace
    s = re.sub(r"\s+", " ", s).strip()
    return s

rouge_metric_single = evaluate.load("rouge")

def calculate_single_rouge_l(prediction, reference):
    # Ensure prediction and reference are strings and not NaN
    if pd.isna(prediction) or pd.isna(reference):
        return None # Or 0.0, depending on how you want to handle missing values

    prediction = normalize_text_single(prediction)
    reference = normalize_text_single(reference)

    # If either is empty after normalization, ROUGE might fail or not be meaningful
    if not prediction or not reference:
        return None

    # rouge_metric_single.compute expects lists of predictions and references
    result = rouge_metric_single.compute(
        predictions=[prediction],
        references=[reference]
    )
    return result["rougeL"] * 100 # Return the single ROUGE-L score

In [27]:
# Calculate ROUGE-L for each prediction type per row
filtered_ground_truth['Top1_ROUGEL'] = filtered_ground_truth.apply(lambda row: calculate_single_rouge_l(row['Top1'], row['Ground truth']), axis=1)
filtered_ground_truth['Top3_ROUGEL'] = filtered_ground_truth.apply(lambda row: calculate_single_rouge_l(row['Top 3'], row['Ground truth']), axis=1)
filtered_ground_truth['Top5_ROUGEL'] = filtered_ground_truth.apply(lambda row: calculate_single_rouge_l(row['Top5'], row['Ground truth']), axis=1)
filtered_ground_truth['LLMOnly_ROUGEL'] = filtered_ground_truth.apply(lambda row: calculate_single_rouge_l(row['LLMOnly'], row['Ground truth']), axis=1)
filtered_ground_truth['RAG_ROUGEL'] = filtered_ground_truth.apply(lambda row: calculate_single_rouge_l(row['RAG'], row['Ground truth']), axis=1)

# Display the DataFrame with new ROUGE-L columns
display(filtered_ground_truth.head())

,Query,question,Ground truth,Kategori,Top 3,Top1,Top5,LLMOnly,RAG,Top1_BERTScore,Top3_BERTScore,Top5_BERTScore,LLMOnly_BERTScore,RAG_BERTScore,Top1_ROUGEL,Top3_ROUGEL,Top5_ROUGEL,LLMOnly_ROUGEL,RAG_ROUGEL
0,1,Informatika itu apa?,Informatika di UHN Sugriwa adalah program stud...,Profil,Halo! Senang bertemu di UHN Sugriwa! Informati...,Halo! Informatika itu ilmu yang asyik banget n...,Hai! Senang bisa bantu ya. Informatika itu kay...,**Informatika adalah ilmu dan seni yang mempel...,**Jawaban:**\n\nInformatika adalah ilmu yang m...,68.463814,70.124251,68.724281,63.069034,69.222838,14.583333,20.202020,11.111111,11.034483,12.345679
1,2,Nanti anak saya kalau mau kuliah informatika b...,Berkuliah di Informatika akan belajar mengenai...,Belajar apa?,Halo! Senang sekali mendengar minat Bapak/Ibu ...,Halo! Senang sekali mendengar kamu tertarik de...,Halo! Senang sekali mendengar kamu tertarik sa...,Untuk mempersiapkan anak Anda menghadapi studi...,Untuk menanggapi pertanyaan Anda mengenai mata...,71.410537,73.420596,68.329823,67.942017,67.797756,14.754098,13.913043,15.254237,9.638554,11.250000
2,3,Peluang kerja ketika lulusan informatika,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Halo! Senang sekali kamu tertarik dengan jurus...,"Halo! Wah, senang sekali kamu tertarik dengan ...",Halo! Senang sekali kamu tertarik sama jurusan...,"Halo! Sebagai lulusan Informatika, peluang kar...",Halo! Terima kasih atas pertanyaannya. Berdasa...,69.110465,70.974064,71.381390,60.728037,62.316221,20.512821,20.689655,20.000000,7.792208,11.688312
3,4,Apa saja peluang pekerjaannya?,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Hai! Senang sekali kamu tertarik sama jurusan ...,"Hai! Wah, senang sekali kamu tertarik sama jur...",Halo! Senang sekali kamu tertarik dengan jurus...,"Halo! Pertanyaan yang bagus. ""Peluang kerja"" b...",Selamat! Sebagai lulusan Prodi Informatika Uni...,70.654625,71.020824,71.377748,61.869234,64.038795,27.826087,24.000000,24.000000,9.395973,10.884354
4,5,Skil apa yang harus dimiliki jika mau jadi fro...,"Untuk menjadi Front-End Developer, perlu mengu...",Umum,Hai! Senang banget kamu tertarik jadi *front-e...,Hai! Senang banget kamu tertarik jadi *front-e...,Hai! Senang banget kamu tertarik jadi *front-e...,Untuk menjadi *front-end developer* (pengemban...,Untuk menjadi *front-end developer* yang kompe...,70.632434,71.192479,65.895331,65.287858,63.480312,23.913043,23.655914,18.181818,16.883117,14.193548

save the DataFrame with the new ROUGE-L columns to a CSV file.

In [28]:
# Save the updated DataFrame to a new CSV file
save_dir = "response_uhn_chatbot"
os.makedirs(save_dir, exist_ok=True)
output_csv_path_rouge = save_dir + "/Groundtruth_ROUGEL_per_query.csv"
filtered_ground_truth.to_csv(output_csv_path_rouge, index=False)
print(f"DataFrame with per-query ROUGE-L saved to: {output_csv_path_rouge}")

DataFrame with per-query ROUGE-L saved to: response_uhn_chatbot/Groundtruth_ROUGEL_per_query.csv

# For additional ablation

In [29]:
# this data is the additional data for ablation test for hard-coded the institutional name
df_with_name = pd.read_csv("./03_Data/GroundTruth_name.csv")
display(df_with_name)

,Query,Questions,Ground truth,Unnamed: 3,LLM+RAG+Name
0,1,Informatika itu apa?,Informatika di UHN Sugriwa adalah program stud...,Profil,Selamat datang di Program Studi Informatika Un...
1,2,Nanti anak saya kalau mau kuliah informatika b...,Berkuliah di Informatika akan belajar mengenai...,Belajar apa?,Selamat datang di Program Studi Informatika Un...
2,3,Peluang kerja ketika lulusan informatika,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Halo! Senang sekali Anda tertarik dengan pelua...
3,4,Apa saja peluang pekerjaannya?,"Setelah lulus, Setelah lulus dari Prodi Inform...",Bidang Kerja,Selamat datang di Program Studi Informatika Un...
4,5,Skil apa yang harus dimiliki jika mau jadi fro...,"Untuk menjadi Front-End Developer, perlu mengu...",Umum,Halo! Senang sekali Anda tertarik dengan Progr...
...,...,...,...,...,...
260,417,kelasnya pagi atau malam?,Seluruh perkuliahan dilaksanakan antara pukul ...,Pelaksanaan Kuliah,Halo! Sebagai pengunjung di Program Studi Info...
261,418,informasi jurusan informatika di uhn,Informatika di UHN Sugriwa adalah program stud...,Profil,Selamat datang di Program Studi Informatika UH...
262,419,Apa saja yang akan saya pelajari dalam jurusan...,Berkuliah di Informatika akan belajar mengenai...,Belajar apa?,Halo! Selamat datang di Program Studi Informat...
263,420,Apakah boleh memilih kampus?,Kampus Ratna Denpasar ada di Jalan Ratna Denpa...,Kampus,"Ya, Anda bisa memilih kampus! Prodi Informatik..."
264,421,"Tapi aku ga ada bakat di bidang itu, apakah bi...","Bisa, dosen akan sangat senang membantu mahasi...",Susah tidak,Halo! Senang sekali Anda tertarik dengan Progr...

In [30]:
# select non na data
total_data_with_name = df_with_name[(df_with_name['Query'].notna())]

In [31]:
# filter data is not na
ground_nan_with_name = total_data_with_name[(total_data_with_name['Ground truth'].isna())]

In [32]:
# select data is not na
filtered_ground_truth_with_name = df_with_name[(df_with_name['Ground truth'].notna())]

In [33]:
# check total data
len(total_data_with_name)

265

In [34]:
#additional code for groundtruth_name.csv
llm_rag_name = filtered_ground_truth_with_name["LLM+RAG+Name"].to_list()
ground_truth_with_name = filtered_ground_truth_with_name["Ground truth"].to_list()

In [35]:
llm_rag_name[0]

'Selamat datang di Program Studi Informatika Universitas Harapan Negeri I Gusti Bagus Sugriwa! Senang sekali Anda bertanya tentang informatika.\n\nJawabannya sederhana saja: Informatika adalah ilmu yang mempelajari cara kita mengolah, menyimpan, dan mendistribusikan informasi menggunakan komputer. Bayangkan seperti ini – dari membuat aplikasi yang sering kamu gunakan sehari-hari hingga sistem pintar yang bisa membantu kita dalam kehidupan sehari-hari.\n\nDi UHN Sugriwa, kami tidak hanya belajar dasar-dasarnya, tapi juga bagaimana menerapkan teknologi untuk solusi nyata. Misalnya, kami fokus pada pengembangan program komputer (perangkat lunak), pembuatan sistem cerdas atau *artificial intelligence* (AI) yang semakin populer, dan tentu saja, bagaimana teknologi bisa disesuaikan dengan kebutuhan dan budaya kita sendiri. Kami percaya bahwa teknologi harus bermanfaat bagi masyarakat Indonesia!\n\nApakah ada hal spesifik yang ingin Anda ketahui lebih lanjut tentang mata kuliah'

In [36]:
ground_truth_with_name[0]

'Informatika di UHN Sugriwa adalah program studi yang menghasilkan lulusan yang mampu menciptakan perangkat lunak, aplikasi bidang AI, atau teknologi lainnya, atau disebut juga Lulusan bisa bekerja sebagai AI Engineer, Software Engineer, Asisten Peneliti. Sehingga bisa membantu mempermudah kehidupan atau pekerjaan masyarakat. '

In [37]:
filtered_ground_truth_with_name['RAG+Name_BERTScore'] = filtered_ground_truth_with_name.apply(lambda row: calculate_single_bertscore_f1(row['LLM+RAG+Name'], row['Ground truth']), axis=1)

In [38]:
# Save the updated DataFrame to a new CSV file
save_dir = "response_uhn_chatbot"
os.makedirs(save_dir, exist_ok=True)
output_csv_path = save_dir + "/Groundtruth_BERTScore_per_query_name.csv"
filtered_ground_truth_with_name.to_csv(output_csv_path, index=False)
print(f"DataFrame with per-query BERTScore saved to: {output_csv_path}")

DataFrame with per-query BERTScore saved to: response_uhn_chatbot/Groundtruth_BERTScore_per_query_name.csv

In [39]:
# for LLM+RAG+name.
llm_rag_name_rouge = calculate_rouge_l(llm_rag_name, ground_truth)

In [40]:
# for LLM_RAG_name
print(f"llm rag name rougeL: {llm_rag_name_rouge}")

llm rag name rougeL: 13.03531885236316

In [41]:
#for LLM_RAG+Name
llm_rag_name_bertscore = calculate_bertscore(llm_rag_name, ground_truth)

In [42]:

print(f"llm rag name only bertscore: {llm_rag_name_bertscore}")

llm rag name only bertscore: 66.70753611708588

In [43]:
#ini khusus untuk LLM+RAG+Name saja
filtered_ground_truth_with_name['RAG+Name_ROUGEL'] = filtered_ground_truth_with_name.apply(lambda row: calculate_single_rouge_l(row['LLM+RAG+Name'], row['Ground truth']), axis=1)

In [44]:
# Save the updated DataFrame to a new CSV file
output_csv_path_rouge = save_dir + "/Groundtruth_ROUGEL_BERTScore_per_query_name.csv"
filtered_ground_truth_with_name.to_csv(output_csv_path_rouge, index=False)
print(f"DataFrame with per-query ROUGE-L saved to: {output_csv_path_rouge}")

DataFrame with per-query ROUGE-L saved to: response_uhn_chatbot/GroundtruthROUGE_BERTScore_per_query_name.csv

In [45]:
results = {
    "Model": ["Top 1", "Top 3", "Top 5", "LLM Only", "LLM RAG Only", "LLM+RAG+Name"],
    "ROUGE_L": [top_1_rouge, top_3_rouge, top_5_rouge, llm_only_rouge, llm_rag_only_rouge, llm_rag_name_rouge],
    "BERTScore": [top_1_bertscore, top_3_bertscore, top_5_bertscore, llm_only_bertscore, llm_rag_only_bertscore, llm_rag_name_bertscore]
}

df_results_final = pd.DataFrame(results)
print(df_results_final)

          Model    ROUGE_L  BERTScore
0         Top 1  14.419673  68.147221
1         Top 3  15.308334  68.267633
2         Top 5  14.417062  67.922754
3      LLM Only  10.613711  64.905874
4  LLM RAG Only  12.538060  66.338235
5  LLM+RAG+Name  13.035319  66.707536